name: report test results

on:
    pull_request:
      branches: [main]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  report_test_results:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Create Test Reporter Summary
        uses: dorny/test-reporter@31a54ee7ebcacc03a09ea97a7e5465a47b84aea5 # v1.9.1
        with:
          name: All Test Results
          path: ${{ github.workspace }}/test_report_combined.json
          reporter: flutter-json
          only-summary: true
          token: ${{ github.token }}
          fail-on-error: false